import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AlertTriangle, CalendarClock, ChevronRight, HeartHandshake, LogOut, Video, ShieldAlert, UserRound } from "lucide-react";
import RaahatLogo from "../components/RaahatLogo";
import { getUser, removeToken, clearUser, api } from "../utils/api";

type CaseItem = { case_id: string; holder: string; priority: string; svi: number; status: string; created_at: string; district: string; state: string };
type Detail = CaseItem & { summary?: string; transcript?: string; indicators?: [string, string][]; factors?: { label: string; value: number; contrib?: string; confidence?: string }[]; consequences?: string };

export default function CounsellorPortal() {
  const nav = useNavigate();
  const [user] = useState(getUser());
  const [cases, setCases] = useState<CaseItem[]>([]);
  const [selected, setSelected] = useState<Detail | null>(null);
  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState(false);

  useEffect(() => {
    if (!user || user.role !== "counsellor") { nav("/login"); return; }
    api.get<{ cases: CaseItem[] }>("/cases?limit=50").then(result => { if (result.ok && result.data) { setCases(result.data.cases); if (result.data.cases[0]) selectCase(result.data.cases[0].case_id); } setLoading(false); });
  }, [nav, user]);

  async function selectCase(caseId: string) { const result = await api.get<Detail>(`/cases/${caseId}`); if (result.ok && result.data) { setSelected(result.data); setSession(false); } }
  function logout() { removeToken(); clearUser(); nav("/"); }
  const riskCount = selected?.indicators?.filter(([, level]) => level === "Critical" || level === "High").length || 0;

  return <div className="min-h-screen bg-slate-50"><header className="bg-navy-950 text-white"><div className="max-w-7xl mx-auto h-14 px-5 flex items-center justify-between"><div className="flex items-center gap-3"><RaahatLogo size={25} showText={false} /><div><div className="font-bold text-sm">RAAHAT Counsellor Workspace</div><div className="text-[10px] text-navy-300">Assigned cases only · Confidential support record</div></div></div><div className="flex items-center gap-3"><div className="hidden sm:block text-right"><div className="text-xs font-semibold">{user?.name}</div><div className="text-[10px] text-navy-300">{user?.designation}</div></div><button onClick={logout} className="flex items-center gap-1 text-xs text-navy-200 hover:text-white"><LogOut size={14} /> Logout</button></div></div></header>
    <main className="max-w-7xl mx-auto px-5 py-6"><div className="mb-6"><h1 className="text-xl font-bold text-navy-900">My counselling cases</h1><p className="text-sm text-slate-500 mt-0.5">Review assigned cases, identify risk flags, and begin a secure virtual counselling session.</p></div>
      <div className="grid lg:grid-cols-[320px_1fr] gap-5"><aside className="bg-white border border-slate-200 rounded-lg overflow-hidden h-fit"><div className="px-4 py-3 border-b border-slate-100 flex justify-between items-center"><h2 className="font-bold text-sm text-navy-900">Assigned to me</h2><span className="text-xs font-mono bg-navy-50 text-navy-700 px-2 py-0.5 rounded">{cases.length}</span></div>{loading ? <div className="p-6 text-sm text-slate-400">Loading cases…</div> : cases.length === 0 ? <div className="p-6 text-sm text-slate-500 text-center">No counselling cases are assigned to you.</div> : <div className="divide-y divide-slate-100">{cases.map(c => <button key={c.case_id} onClick={() => selectCase(c.case_id)} className={`w-full text-left px-4 py-3 hover:bg-navy-50 ${selected?.case_id === c.case_id ? "bg-navy-50 border-l-2 border-navy-800" : ""}`}><div className="flex justify-between gap-2"><span className="text-sm font-semibold text-navy-900">{c.holder}</span><span className={`text-[10px] font-bold ${c.svi >= 80 ? "text-critical-700" : "text-amber-700"}`}>SVI {c.svi}</span></div><div className="text-xs text-slate-500 font-mono mt-1">{c.case_id}</div><div className="text-xs text-slate-500 mt-1">{c.district}, {c.state}</div></button>)}</div>}</aside>
      <section>{!selected ? <div className="bg-white border border-slate-200 rounded-lg p-10 text-center text-slate-400">Select an assigned case to begin review.</div> : <div className="space-y-5"><div className="bg-white border border-slate-200 rounded-lg p-5 flex flex-wrap justify-between gap-4"><div><div className="text-xs font-mono text-slate-400">{selected.case_id}</div><h2 className="text-lg font-bold text-navy-900 mt-1">{selected.holder}</h2><p className="text-sm text-slate-500">{selected.district}, {selected.state} · {selected.status}</p></div><button onClick={() => setSession(!session)} className={`flex items-center gap-2 h-fit px-4 py-2.5 rounded text-sm font-semibold ${session ? "bg-safe-700 text-white" : "bg-navy-900 text-white hover:bg-navy-800"}`}><Video size={16} />{session ? "Virtual session active" : "Start virtual counselling"}</button></div>
        {session && <div className="bg-safe-50 border border-safe-200 rounded-lg p-4 flex items-start gap-3"><HeartHandshake className="text-safe-700 shrink-0" size={19} /><div><div className="font-semibold text-sm text-safe-800">Secure virtual counselling room ready</div><p className="text-xs text-safe-700 mt-1">Verify the person's identity and consent before discussing their case. Session notes should be recorded through the approved clinical process.</p></div></div>}
        <div className="grid md:grid-cols-3 gap-4"><div className={`rounded-lg border p-4 ${selected.svi >= 80 ? "bg-critical-50 border-critical-200" : "bg-amber-50 border-amber-200"}`}><div className="text-xs text-slate-600">Stress Vulnerability Index</div><div className={`font-mono text-3xl font-bold mt-1 ${selected.svi >= 80 ? "text-critical-700" : "text-amber-700"}`}>{selected.svi}<span className="text-sm"> / 100</span></div><div className="text-xs text-slate-600 mt-1">Prioritization aid — not a diagnosis</div></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-1.5 text-xs text-amber-800"><ShieldAlert size={14} />Active risk flags</div><div className="font-mono text-3xl font-bold text-amber-800 mt-1">{riskCount}</div><div className="text-xs text-amber-700 mt-1">High or critical indicators detected</div></div><div className="rounded-lg border border-navy-100 bg-navy-50 p-4"><div className="flex items-center gap-1.5 text-xs text-navy-700"><CalendarClock size={14} />Next action</div><div className="text-sm font-semibold text-navy-900 mt-2">Safety check & counselling</div><div className="text-xs text-slate-600 mt-1">Confirm immediate needs before the session.</div></div></div>
        <div className="grid md:grid-cols-2 gap-5"><div className="bg-white border border-slate-200 rounded-lg p-5"><h3 className="font-bold text-sm text-navy-900">SVI breakdown</h3><p className="text-xs text-slate-500 mt-1 mb-4">Signals contributing to the prioritization score.</p><div className="space-y-3">{selected.factors?.length ? selected.factors.map(f => <div key={f.label}><div className="flex justify-between text-xs"><span className="text-slate-700">{f.label}</span><span className="font-mono font-bold text-navy-800">{f.value}</span></div><div className="h-1.5 bg-slate-100 rounded-full mt-1"><div className="h-full bg-navy-700 rounded-full" style={{ width: `${Math.min(100, f.value)}%` }} /></div></div>) : <p className="text-sm text-slate-400">No factor breakdown is available.</p>}</div></div><div className="bg-white border border-slate-200 rounded-lg p-5"><h3 className="font-bold text-sm text-navy-900">Risk flags</h3><p className="text-xs text-slate-500 mt-1 mb-4">Review these with professional judgement.</p><div className="space-y-2">{selected.indicators?.length ? selected.indicators.map(([label, level]) => <div key={label} className="flex justify-between gap-3 rounded border border-slate-100 bg-slate-50 px-3 py-2"><span className="text-xs text-slate-700">{label}</span><span className={`text-xs font-bold ${level === "Critical" ? "text-critical-700" : level === "High" ? "text-amber-700" : "text-navy-700"}`}>{level}</span></div>) : <p className="text-sm text-slate-400">No risk flags are available.</p>}</div></div></div>
        <div className="bg-white border border-slate-200 rounded-lg p-5"><div className="flex items-center gap-2"><AlertTriangle size={16} className="text-amber-700" /><h3 className="font-bold text-sm text-navy-900">Case overview</h3></div><p className="text-sm text-slate-700 leading-relaxed mt-3">{selected.summary || "No AI assessment summary is available."}</p><p className="text-xs text-critical-700 font-medium mt-3">{selected.consequences}</p></div>
      </div>}</section></div>
    </main></div>;
}
